# name: Gitleaks Secret Scan

# on:
#   push:
#   pull_request:

# jobs:
#   scan:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Install Gitleaks
#         run: |
#           curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
#           chmod +x gitleaks

#       - name: Run Gitleaks (Generate SARIF Report)
#         run: |
#           ./gitleaks detect \
#             --source . \
#             --report-format sarif \
#             --report-path gitleaks-report.sarif \
#             --no-banner
#         continue-on-error: true

#       - name: Upload SARIF Report to GitHub Security Dashboard
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: gitleaks-report.sarif


name: Gitleaks Secret Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path reports/gitleaks-report.sarif

      - name: Debug reports
        run: ls -lah reports

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/gitleaks-report.sarif



